name: Ominakavsar_CI_Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validation:
    name: Code Validation
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Python Environment Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Dependency Injection
        run: pip install -r requirements.txt

      - name: Execute Tests
        run: python3 -m pytest tests/ --tb=line

  container-build:
    name: Docker Image Verification
    runs-on: ubuntu-latest
    needs: [validation]
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Build Local Image
        run: docker build -t cloud-lab-omina:${{ github.run_id }} .
